### ISSUE TITLE
error

### ISSUE THREAD

**Issue by leejunghan** [socib/NC2KML#1]
Hi I'm Jung-Han Lee.
I compiled the Testing.java in the test folder. But I can't fix the error.
Could you help me please?

C:\Users\LJH-PC\Downloads\NC2KML-master\NC2KML-master

NC2KML-master
                 -> lib
                 -> release
                 -> src
                  ->test

-------------------------------------------------------------------------------------------------------
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. All rights reserved.

C:\Users\LJH-PC>cd C:\Users\LJH-PC\Downloads\NC2KML-master\NC2KML-master\test\ne
tcdftokml\test

C:\Users\LJH-PC\Downloads\NC2KML-master\NC2KML-master\test\netcdftokml\test>java
c Testing.java
Testing.java:9: error: package org.apache.log4j does not exist
import org.apache.log4j.Logger;
                       ^
Testing.java:10: error: package org.apache.log4j does not exist
import org.apache.log4j.PropertyConfigurator;
                       ^
Testing.java:12: error: package ucar.nc2.dataset does not exist
import ucar.nc2.dataset.NetcdfDataset;
                       ^
Testing.java:13: error: package es.socib.netcdftokml does not exist
import es.socib.netcdftokml.AdditionalInfo;
                           ^
Testing.java:14: error: package es.socib.netcdftokml does not exist
import es.socib.netcdftokml.DeploymentInfo;
                           ^
Testing.java:15: error: package es.socib.netcdftokml does not exist
import es.socib.netcdftokml.KmlManager;
                           ^
Testing.java:16: error: package es.socib.netcdftokml does not exist
import es.socib.netcdftokml.KmlManagerException;
                           ^
Testing.java:23: error: cannot find symbol
        private static Logger logger = Logger.getLogger(Testing.class.getSimpleN
ame());
                       ^
  symbol:   class Logger
  location: class Testing
Testing.java:23: error: cannot find symbol
        private static Logger logger = Logger.getLogger(Testing.class.getSimpleN
ame());
                                       ^
  symbol:   variable Logger
  location: class Testing
Testing.java:34: error: cannot find symbol
                InputStream stream = KmlManager.class.getResourceAsStream("/log4
j_kmz.properties");
                                     ^
  symbol:   class KmlManager
  location: class Testing
Testing.java:41: error: cannot find symbol
                PropertyConfigurator.configure(properties);
                ^
  symbol:   variable PropertyConfigurator
  location: class Testing
Testing.java:65: error: cannot find symbol
                        DeploymentInfo deploymentInfo = DeploymentInfo.createDep
loymentInfo("1 day since 2011-09-07 00:00:00", "3.400", "39.200");
                        ^
  symbol:   class DeploymentInfo
  location: class Testing
Testing.java:65: error: cannot find symbol
                        DeploymentInfo deploymentInfo = DeploymentInfo.createDep
loymentInfo("1 day since 2011-09-07 00:00:00", "3.400", "39.200");
                                                        ^
  symbol:   variable DeploymentInfo
  location: class Testing
Testing.java:66: error: cannot find symbol
                        AdditionalInfo additionalInfo = new AdditionalInfo(deplo
ymentInfo, null, null, false);
                        ^
  symbol:   class AdditionalInfo
  location: class Testing
Testing.java:66: error: cannot find symbol
                        AdditionalInfo additionalInfo = new AdditionalInfo(deplo
ymentInfo, null, null, false);
                                                            ^
  symbol:   class AdditionalInfo
  location: class Testing
Testing.java:67: error: cannot find symbol
                        KmlManager kmlManager = new KmlManager(NetcdfDataset.ope
nDataset(netCdfFileLocation), additionalInfo, kmlFileLocation);
                        ^
  symbol:   class KmlManager
  location: class Testing
Testing.java:67: error: cannot find symbol
                        KmlManager kmlManager = new KmlManager(NetcdfDataset.ope
nDataset(netCdfFileLocation), additionalInfo, kmlFileLocation);
                                                    ^
  symbol:   class KmlManager
  location: class Testing
Testing.java:67: error: cannot find symbol
                        KmlManager kmlManager = new KmlManager(NetcdfDataset.ope
nDataset(netCdfFileLocation), additionalInfo, kmlFileLocation);
                                                               ^
  symbol:   variable NetcdfDataset
  location: class Testing
Testing.java:69: error: cannot find symbol
                } catch (KmlManagerException e) {
                         ^
  symbol:   class KmlManagerException
  location: class Testing
19 errors

C:\Users\LJH-PC\Downloads\NC2KML-master\NC2KML-master\test\netcdftokml\test>

**Comment by JuangaSocib** [comment]
Dear Jung-Hang, we have discovered that the release/NC2KML.jar file wasn't up-to-date after the last update of our code. Now it's fixed. Also I suggest you don't forget to include the dependencies classpath parameter while using "javac -cp": 
`javac -cp "../../../lib/*;../../../release/*" Testing.java`

Thank you very much for using our projects and for your contribution.

**Comment by leejunghan** [comment]
Thank you very much.. 
I have successfully compiled a Testing.java and created a Testing.class in the test folder.
But I can't build Testing.class.

Build error message is "can't not find Testing class"

I tried do my best...and googling.. but I failed.. 
sorry could you help me?

Below is my java setting.
<variables>               < value>
CLASSPATH       .;%JAVA_HOME%\lib
JAVA_HOME     C:\Program Files\Java\jdk1.8.0_131
PATH                %JAVA_HOME%\bin;

**Comment by leejunghan** [comment]
Dear JuangaSocib
 
I compiled as your instruction. As a result,the class files are made. 
I build the Testing.class..but the errors exist.
Could you help me?
 
Thanks
 
Jung-Han
 
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 
C:\Users\LJH-PC\Downloads\NC2KML-master\NC2KML-master\test
etcdftokml\test>javac -cp "C:\Users\LJH-PC\Downloads\NC2KML-master\NC2KML-master\lib/*;C:\Users\LJH-PC\Downloads\NC2KML-master\NC2KML-master\release/*" Testing.java
 
C:\Users\LJH-PC\Downloads\NC2KML-master\NC2KML-master\test
etcdftokml\test>cd..
 
C:\Users\LJH-PC\Downloads\NC2KML-master\NC2KML-master\test
etcdftokml>cd..
 
C:\Users\LJH-PC\Downloads\NC2KML-master\NC2KML-master\test>java netcdftokml.test.Testing
 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: es/socib/netcdftokml/KmlManagerException
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
at java.lang.Class.privateGetMethodRecursive(Unknown Source)
at java.lang.Class.getMethod0(Unknown Source)
at java.lang.Class.getMethod(Unknown Source)
at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: es.socib.netcdftokml.KmlManagerException
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 7 more
 
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


 
 
 
 
 
 

 
--- Original Message ---
From : "JuangaSocib"<notifications@github.com>
To : "socib/NC2KML"<NC2KML@noreply.github.com>
Cc : "leejunghan"<leejunghan@kiost.ac.kr>, "Author"<author@noreply.github.com>
Date : 2017/06/07 수요일 오후 11:06:36
Subject : Re: [socib/NC2KML] error (#1)

Dear Jung-Hang, we have discovered that the release/NC2KML.jar file wasn't up-to-date after the last update of our code. Now it's fixed. Also I suggest you don't forget to include the dependencies classpath parameter while using "javac -cp":
javac -cp "../../../lib/*;../../../release/*" Testing.java
Thank you very much for using our projects and for your contribution.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/socib/NC2KML","title":"socib/NC2KML","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/socib/NC2KML"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JuangaSocib in #1: Dear Jung-Hang, we have discovered that the release/NC2KML.jar file wasn't up-to-date after the last update of our code. Now it's fixed. Also I suggest you don't forget to include the dependencies classpath parameter while using \"javac -cp\": \r
`javac -cp \"../../../lib/*;../../../release/*\" Testing.java`\r
\r
Thank you very much for using our projects and for your contribution."}],"action":{"name":"View Issue","url":"https://github.com/socib/NC2KML/issues/1#issuecomment-306805485"}}}
